// Seed-Daten für die Beispiel-Datenbank
import type { PrismaClient } from '../generated/prisma/client.js';
import { getLogger } from '../logger/logger.js';

export const seedDatabase = async (prisma: PrismaClient) => {
    const logger = getLogger('seedDatabase');

    const books = [
        {
            isbn: '9783161484100',
            titel: 'Programmieren mit TypeScript',
            untertitel: 'Grundlagen und Praxis',
            rating: 4,
            preis: '29.90',
            rabatt: '0.100',
            lieferbar: true,
            datum: new Date('2020-01-15'),
            homepage: 'https://example.com/ts1',
            schlagwoerter: ['typescript', 'programming'],
        },
        {
            isbn: '9783161484101',
            titel: 'Einführung in NestJS',
            untertitel: 'Server-seitige Entwicklung',
            rating: 5,
            preis: '34.50',
            rabatt: '0.150',
            lieferbar: true,
            datum: new Date('2021-04-10'),
            homepage: 'https://example.com/nest1',
            schlagwoerter: ['nest', 'nodejs'],
        },
        {
            isbn: '9783161484102',
            titel: 'Datenbanken mit Prisma',
            untertitel: 'ORM praktisch',
            rating: 3,
            preis: '24.00',
            rabatt: '0.050',
            lieferbar: true,
            datum: new Date('2022-06-21'),
            homepage: 'https://example.com/prisma1',
            schlagwoerter: ['prisma', 'database'],
        },
        {
            isbn: '9783161484103',
            titel: 'Angular für Einsteiger',
            untertitel: 'Frontend mit Komponenten',
            rating: 4,
            preis: '27.50',
            rabatt: '0.120',
            lieferbar: true,
            datum: new Date('2019-11-11'),
            homepage: 'https://example.com/angular1',
            schlagwoerter: ['angular', 'frontend'],
        },
        {
            isbn: '9783161484104',
            titel: 'Sichere Webanwendungen',
            untertitel: 'Best Practices',
            rating: 5,
            preis: '39.90',
            rabatt: '0.200',
            lieferbar: true,
            datum: new Date('2018-08-05'),
            homepage: 'https://example.com/security1',
            schlagwoerter: ['security', 'web'],
        },
        {
            isbn: '9783161484105',
            titel: 'Microservices in der Praxis',
            untertitel: 'Architekturen und Patterns',
            rating: 4,
            preis: '31.00',
            rabatt: '0.080',
            lieferbar: true,
            datum: new Date('2020-03-30'),
            homepage: 'https://example.com/micro1',
            schlagwoerter: ['microservices', 'architecture'],
        },
        {
            isbn: '9783161484106',
            titel: 'Test-Driven Development',
            untertitel: 'Tests effektiv einsetzen',
            rating: 3,
            preis: '21.00',
            rabatt: '0.050',
            lieferbar: true,
            datum: new Date('2017-12-01'),
            homepage: 'https://example.com/tdd1',
            schlagwoerter: ['tdd', 'testing'],
        },
        {
            isbn: '9783161484107',
            titel: 'REST APIs gestalten',
            untertitel: 'Konventionen und Design',
            rating: 4,
            preis: '26.40',
            rabatt: '0.070',
            lieferbar: true,
            datum: new Date('2021-02-14'),
            homepage: 'https://example.com/rest1',
            schlagwoerter: ['rest', 'api'],
        },
        {
            isbn: '9783161484108',
            titel: 'GraphQL kompakt',
            untertitel: 'Abfragen effizient gestalten',
            rating: 4,
            preis: '22.00',
            rabatt: '0.060',
            lieferbar: true,
            datum: new Date('2022-09-09'),
            homepage: 'https://example.com/graphql1',
            schlagwoerter: ['graphql', 'api'],
        },
        {
            isbn: '9783161484109',
            titel: 'DevOps Grundlagen',
            untertitel: 'CI/CD und Automatisierung',
            rating: 5,
            preis: '35.00',
            rabatt: '0.150',
            lieferbar: true,
            datum: new Date('2018-04-20'),
            homepage: 'https://example.com/devops1',
            schlagwoerter: ['devops', 'ci'],
        },
        {
            isbn: '9783161484110',
            titel: 'Clean Code',
            untertitel: 'Lesbarer Code schreiben',
            rating: 5,
            preis: '29.00',
            rabatt: '0.100',
            lieferbar: true,
            datum: new Date('2008-08-01'),
            homepage: 'https://example.com/cleancode',
            schlagwoerter: ['clean', 'code'],
        },
        {
            isbn: '9783161484111',
            titel: 'Refactoring',
            untertitel: 'Verbessern vorhandenen Codes',
            rating: 4,
            preis: '33.00',
            rabatt: '0.090',
            lieferbar: true,
            datum: new Date('2012-05-15'),
            homepage: 'https://example.com/refactor',
            schlagwoerter: ['refactor', 'design'],
        },
        {
            isbn: '9783161484112',
            titel: 'Kubernetes praktisch',
            untertitel: 'Container orchestrieren',
            rating: 4,
            preis: '38.00',
            rabatt: '0.110',
            lieferbar: true,
            datum: new Date('2020-10-10'),
            homepage: 'https://example.com/k8s1',
            schlagwoerter: ['kubernetes', 'containers'],
        },
        {
            isbn: '9783161484113',
            titel: 'Agile Methoden',
            untertitel: 'Scrum und Kanban',
            rating: 3,
            preis: '18.50',
            rabatt: '0.040',
            lieferbar: true,
            datum: new Date('2016-07-07'),
            homepage: 'https://example.com/agile1',
            schlagwoerter: ['agile', 'scrum'],
        },
        {
            isbn: '9783161484114',
            titel: 'Software-Architektur',
            untertitel: 'Patterns und Prinzipien',
            rating: 5,
            preis: '41.00',
            rabatt: '0.180',
            lieferbar: true,
            datum: new Date('2015-03-03'),
            homepage: 'https://example.com/arch1',
            schlagwoerter: ['architecture', 'patterns'],
        },
        {
            isbn: '9783161484115',
            titel: 'Scripting mit Bash',
            untertitel: 'Automatisierung im Alltag',
            rating: 2,
            preis: '15.00',
            rabatt: '0.020',
            lieferbar: true,
            datum: new Date('2014-01-20'),
            homepage: 'https://example.com/bash1',
            schlagwoerter: ['bash', 'scripting'],
        },
        {
            isbn: '9783161484116',
            titel: 'Machine Learning Basics',
            untertitel: 'Algorithmen und Modelle',
            rating: 4,
            preis: '36.50',
            rabatt: '0.130',
            lieferbar: true,
            datum: new Date('2019-09-09'),
            homepage: 'https://example.com/ml1',
            schlagwoerter: ['ml', 'ai'],
        },
        {
            isbn: '9783161484117',
            titel: 'Docker kompakt',
            untertitel: 'Container-Workflows',
            rating: 3,
            preis: '19.00',
            rabatt: '0.050',
            lieferbar: true,
            datum: new Date('2018-02-02'),
            homepage: 'https://example.com/docker1',
            schlagwoerter: ['docker', 'containers'],
        },
        {
            isbn: '9783161484118',
            titel: 'Netzwerke verständlich',
            untertitel: 'Grundlagen der Netzwerktechnik',
            rating: 3,
            preis: '23.00',
            rabatt: '0.060',
            lieferbar: true,
            datum: new Date('2013-06-06'),
            homepage: 'https://example.com/net1',
            schlagwoerter: ['networking', 'tcpip'],
        },
        {
            isbn: '9783161484119',
            titel: 'Python für Data Science',
            untertitel: 'Datenanalyse mit Python',
            rating: 5,
            preis: '42.00',
            rabatt: '0.150',
            lieferbar: true,
            datum: new Date('2021-05-15'),
            homepage: 'https://example.com/python-ds',
            schlagwoerter: ['python', 'data-science'],
        },
        {
            isbn: '9783161484120',
            titel: 'React Patterns',
            untertitel: 'Moderne React-Entwicklung',
            rating: 4,
            preis: '33.50',
            rabatt: '0.100',
            lieferbar: true,
            datum: new Date('2022-03-20'),
            homepage: 'https://example.com/react',
            schlagwoerter: ['react', 'javascript'],
        },
        {
            isbn: '9783161484121',
            titel: 'Vue.js 3 kompakt',
            untertitel: 'Progressive Framework',
            rating: 4,
            preis: '28.00',
            rabatt: '0.080',
            lieferbar: true,
            datum: new Date('2021-11-10'),
            homepage: 'https://example.com/vue',
            schlagwoerter: ['vue', 'frontend'],
        },
        {
            isbn: '9783161484122',
            titel: 'MongoDB Essentials',
            untertitel: 'NoSQL-Datenbanken',
            rating: 3,
            preis: '26.50',
            rabatt: '0.070',
            lieferbar: true,
            datum: new Date('2020-08-08'),
            homepage: 'https://example.com/mongo',
            schlagwoerter: ['mongodb', 'nosql'],
        },
        {
            isbn: '9783161484123',
            titel: 'Continuous Delivery',
            untertitel: 'Reliable Software Releases',
            rating: 5,
            preis: '44.00',
            rabatt: '0.160',
            lieferbar: true,
            datum: new Date('2017-09-12'),
            homepage: 'https://example.com/cd',
            schlagwoerter: ['cd', 'devops'],
        },
        {
            isbn: '9783161484124',
            titel: 'Git für Profis',
            untertitel: 'Versionskontrolle meistern',
            rating: 4,
            preis: '22.50',
            rabatt: '0.060',
            lieferbar: true,
            datum: new Date('2019-04-04'),
            homepage: 'https://example.com/git',
            schlagwoerter: ['git', 'vcs'],
        },
        {
            isbn: '9783161484125',
            titel: 'Domain-Driven Design',
            untertitel: 'Softwareentwicklung strategisch',
            rating: 5,
            preis: '48.00',
            rabatt: '0.200',
            lieferbar: true,
            datum: new Date('2015-07-22'),
            homepage: 'https://example.com/ddd',
            schlagwoerter: ['ddd', 'architecture'],
        },
        {
            isbn: '9783161484126',
            titel: 'Linux Administration',
            untertitel: 'Server betreiben',
            rating: 4,
            preis: '35.00',
            rabatt: '0.110',
            lieferbar: true,
            datum: new Date('2018-10-30'),
            homepage: 'https://example.com/linux',
            schlagwoerter: ['linux', 'admin'],
        },
        {
            isbn: '9783161484127',
            titel: 'Functional Programming',
            untertitel: 'Konzepte und Patterns',
            rating: 3,
            preis: '31.00',
            rabatt: '0.090',
            lieferbar: true,
            datum: new Date('2016-12-15'),
            homepage: 'https://example.com/fp',
            schlagwoerter: ['functional', 'programming'],
        },
        {
            isbn: '9783161484128',
            titel: 'Cloud Native Patterns',
            untertitel: 'Designing Applications',
            rating: 5,
            preis: '39.00',
            rabatt: '0.140',
            lieferbar: true,
            datum: new Date('2021-08-18'),
            homepage: 'https://example.com/cloud-native',
            schlagwoerter: ['cloud', 'patterns'],
        },
        {
            isbn: '9783161484129',
            titel: 'JavaScript: The Good Parts',
            untertitel: 'Best Practices',
            rating: 4,
            preis: '24.00',
            rabatt: '0.070',
            lieferbar: true,
            datum: new Date('2011-05-25'),
            homepage: 'https://example.com/js-good',
            schlagwoerter: ['javascript', 'best-practices'],
        },
        {
            isbn: '9783161484130',
            titel: 'Redis in Action',
            untertitel: 'Key-Value Store nutzen',
            rating: 4,
            preis: '29.00',
            rabatt: '0.080',
            lieferbar: true,
            datum: new Date('2019-06-14'),
            homepage: 'https://example.com/redis',
            schlagwoerter: ['redis', 'cache'],
        },
        {
            isbn: '9783161484131',
            titel: 'PostgreSQL Praxis',
            untertitel: 'Relationale Datenbanken',
            rating: 5,
            preis: '37.50',
            rabatt: '0.120',
            lieferbar: true,
            datum: new Date('2020-09-09'),
            homepage: 'https://example.com/postgres',
            schlagwoerter: ['postgresql', 'sql'],
        },
        {
            isbn: '9783161484132',
            titel: 'Serverless Architecture',
            untertitel: 'FaaS und mehr',
            rating: 3,
            preis: '32.00',
            rabatt: '0.100',
            lieferbar: true,
            datum: new Date('2022-01-20'),
            homepage: 'https://example.com/serverless',
            schlagwoerter: ['serverless', 'faas'],
        },
        {
            isbn: '9783161484133',
            titel: 'WebAssembly kompakt',
            untertitel: 'Performance im Browser',
            rating: 4,
            preis: '27.00',
            rabatt: '0.075',
            lieferbar: true,
            datum: new Date('2021-07-07'),
            homepage: 'https://example.com/wasm',
            schlagwoerter: ['wasm', 'performance'],
        },
        {
            isbn: '9783161484134',
            titel: 'Terraform Basics',
            untertitel: 'Infrastructure as Code',
            rating: 4,
            preis: '30.00',
            rabatt: '0.090',
            lieferbar: true,
            datum: new Date('2020-11-11'),
            homepage: 'https://example.com/terraform',
            schlagwoerter: ['terraform', 'iac'],
        },
        {
            isbn: '9783161484135',
            titel: 'Elm Programming',
            untertitel: 'Functional Frontend',
            rating: 3,
            preis: '25.00',
            rabatt: '0.065',
            lieferbar: true,
            datum: new Date('2019-02-28'),
            homepage: 'https://example.com/elm',
            schlagwoerter: ['elm', 'functional'],
        },
        {
            isbn: '9783161484136',
            titel: 'Svelte Framework',
            untertitel: 'Compiler-basiert entwickeln',
            rating: 4,
            preis: '26.00',
            rabatt: '0.070',
            lieferbar: true,
            datum: new Date('2022-04-15'),
            homepage: 'https://example.com/svelte',
            schlagwoerter: ['svelte', 'frontend'],
        },
        {
            isbn: '9783161484137',
            titel: 'AWS Cloud Practitioner',
            untertitel: 'Amazon Web Services',
            rating: 5,
            preis: '41.00',
            rabatt: '0.150',
            lieferbar: true,
            datum: new Date('2021-10-10'),
            homepage: 'https://example.com/aws',
            schlagwoerter: ['aws', 'cloud'],
        },
        {
            isbn: '9783161484138',
            titel: 'Azure Fundamentals',
            untertitel: 'Microsoft Cloud Platform',
            rating: 4,
            preis: '38.50',
            rabatt: '0.130',
            lieferbar: true,
            datum: new Date('2020-12-05'),
            homepage: 'https://example.com/azure',
            schlagwoerter: ['azure', 'cloud'],
        },
        {
            isbn: '9783161484139',
            titel: 'Rust Programming',
            untertitel: 'Systems Programming',
            rating: 5,
            preis: '43.00',
            rabatt: '0.160',
            lieferbar: true,
            datum: new Date('2021-03-18'),
            homepage: 'https://example.com/rust',
            schlagwoerter: ['rust', 'systems'],
        },
        {
            isbn: '9783161484140',
            titel: 'Go Concurrency',
            untertitel: 'Goroutines und Channels',
            rating: 4,
            preis: '34.00',
            rabatt: '0.110',
            lieferbar: true,
            datum: new Date('2020-06-22'),
            homepage: 'https://example.com/go',
            schlagwoerter: ['go', 'concurrency'],
        },
        {
            isbn: '9783161484141',
            titel: 'Flutter Development',
            untertitel: 'Cross-Platform Apps',
            rating: 4,
            preis: '36.00',
            rabatt: '0.120',
            lieferbar: true,
            datum: new Date('2022-02-14'),
            homepage: 'https://example.com/flutter',
            schlagwoerter: ['flutter', 'mobile'],
        },
        {
            isbn: '9783161484142',
            titel: 'Kotlin für Android',
            untertitel: 'Moderne App-Entwicklung',
            rating: 5,
            preis: '40.00',
            rabatt: '0.145',
            lieferbar: true,
            datum: new Date('2021-09-01'),
            homepage: 'https://example.com/kotlin',
            schlagwoerter: ['kotlin', 'android'],
        },
        {
            isbn: '9783161484143',
            titel: 'Swift Programming',
            untertitel: 'iOS Apps entwickeln',
            rating: 4,
            preis: '37.00',
            rabatt: '0.125',
            lieferbar: true,
            datum: new Date('2020-04-04'),
            homepage: 'https://example.com/swift',
            schlagwoerter: ['swift', 'ios'],
        },
        {
            isbn: '9783161484144',
            titel: 'Elasticsearch Guide',
            untertitel: 'Search and Analytics',
            rating: 4,
            preis: '33.00',
            rabatt: '0.105',
            lieferbar: true,
            datum: new Date('2019-08-20'),
            homepage: 'https://example.com/elastic',
            schlagwoerter: ['elasticsearch', 'search'],
        },
        {
            isbn: '9783161484145',
            titel: 'RabbitMQ Essentials',
            untertitel: 'Message Queues nutzen',
            rating: 3,
            preis: '28.50',
            rabatt: '0.085',
            lieferbar: true,
            datum: new Date('2018-11-11'),
            homepage: 'https://example.com/rabbitmq',
            schlagwoerter: ['rabbitmq', 'messaging'],
        },
        {
            isbn: '9783161484146',
            titel: 'Apache Kafka Streams',
            untertitel: 'Event Streaming Platform',
            rating: 5,
            preis: '45.00',
            rabatt: '0.170',
            lieferbar: true,
            datum: new Date('2021-06-30'),
            homepage: 'https://example.com/kafka',
            schlagwoerter: ['kafka', 'streaming'],
        },
        {
            isbn: '9783161484147',
            titel: 'Nginx Cookbook',
            untertitel: 'Webserver konfigurieren',
            rating: 4,
            preis: '29.00',
            rabatt: '0.090',
            lieferbar: true,
            datum: new Date('2019-12-12'),
            homepage: 'https://example.com/nginx',
            schlagwoerter: ['nginx', 'webserver'],
        },
        {
            isbn: '9783161484148',
            titel: 'Apache Spark Guide',
            untertitel: 'Big Data Processing',
            rating: 4,
            preis: '46.00',
            rabatt: '0.180',
            lieferbar: true,
            datum: new Date('2020-07-25'),
            homepage: 'https://example.com/spark',
            schlagwoerter: ['spark', 'bigdata'],
        },
        {
            isbn: '9783161484149',
            titel: 'Jenkins Pipeline',
            untertitel: 'CI/CD Automation',
            rating: 3,
            preis: '27.50',
            rabatt: '0.075',
            lieferbar: true,
            datum: new Date('2018-05-18'),
            homepage: 'https://example.com/jenkins',
            schlagwoerter: ['jenkins', 'ci/cd'],
        },
        {
            isbn: '9783161484150',
            titel: 'Rust Programming',
            untertitel: 'Systems Programming',
            rating: 5,
            preis: '42.90',
            rabatt: '0.120',
            lieferbar: true,
            datum: new Date('2023-01-10'),
            homepage: 'https://example.com/rust',
            schlagwoerter: ['rust', 'systems'],
        },
        {
            isbn: '9783161484151',
            titel: 'Go Microservices',
            untertitel: 'Cloud Native Development',
            rating: 4,
            preis: '38.50',
            rabatt: '0.100',
            lieferbar: true,
            datum: new Date('2023-02-15'),
            homepage: 'https://example.com/go-micro',
            schlagwoerter: ['go', 'microservices'],
        },
        {
            isbn: '9783161484152',
            titel: 'Elixir & Phoenix',
            untertitel: 'Functional Web Development',
            rating: 4,
            preis: '35.00',
            rabatt: '0.090',
            lieferbar: true,
            datum: new Date('2023-03-20'),
            homepage: 'https://example.com/elixir',
            schlagwoerter: ['elixir', 'phoenix'],
        },
        {
            isbn: '9783161484153',
            titel: 'Kotlin for Android',
            untertitel: 'Modern Android Development',
            rating: 5,
            preis: '40.00',
            rabatt: '0.110',
            lieferbar: true,
            datum: new Date('2023-04-05'),
            homepage: 'https://example.com/kotlin',
            schlagwoerter: ['kotlin', 'android'],
        },
        {
            isbn: '9783161484154',
            titel: 'Svelte & SvelteKit',
            untertitel: 'Reactive Frontend Framework',
            rating: 4,
            preis: '33.50',
            rabatt: '0.085',
            lieferbar: true,
            datum: new Date('2023-05-12'),
            homepage: 'https://example.com/svelte',
            schlagwoerter: ['svelte', 'frontend'],
        },
        {
            isbn: '9783161484155',
            titel: 'WebAssembly Deep Dive',
            untertitel: 'High-Performance Web Applications',
            rating: 5,
            preis: '45.00',
            rabatt: '0.130',
            lieferbar: true,
            datum: new Date('2023-06-18'),
            homepage: 'https://example.com/wasm',
            schlagwoerter: ['webassembly', 'performance'],
        },
        {
            isbn: '9783161484156',
            titel: 'Deno Runtime',
            untertitel: 'Secure JavaScript/TypeScript Runtime',
            rating: 4,
            preis: '31.90',
            rabatt: '0.075',
            lieferbar: true,
            datum: new Date('2023-07-22'),
            homepage: 'https://example.com/deno',
            schlagwoerter: ['deno', 'typescript'],
        },
        {
            isbn: '9783161484157',
            titel: 'GraphQL Advanced',
            untertitel: 'Schema Design & Performance',
            rating: 5,
            preis: '39.90',
            rabatt: '0.105',
            lieferbar: true,
            datum: new Date('2023-08-30'),
            homepage: 'https://example.com/graphql-adv',
            schlagwoerter: ['graphql', 'api'],
        },
        {
            isbn: '9783161484158',
            titel: 'Terraform Infrastructure',
            untertitel: 'Infrastructure as Code Mastery',
            rating: 4,
            preis: '44.50',
            rabatt: '0.125',
            lieferbar: true,
            datum: new Date('2023-09-15'),
            homepage: 'https://example.com/terraform',
            schlagwoerter: ['terraform', 'iac'],
        },
    ];

    let inserted = 0;
    for (const b of books) {
        try {
            const exists = await prisma.buch.findUnique({
                where: { isbn: b.isbn },
            });
            if (exists) {
                logger.debug('skip existing isbn=%s', b.isbn);
                continue;
            }

            await prisma.buch.create({
                data: {
                    isbn: b.isbn,
                    rating: b.rating,
                    preis: b.preis,
                    rabatt: b.rabatt,
                    lieferbar: b.lieferbar,
                    datum: b.datum,
                    homepage: b.homepage,
                    schlagwoerter: b.schlagwoerter as any, // Type cast for Prisma JSONB compatibility
                    titel: {
                        create: { titel: b.titel, untertitel: b.untertitel },
                    },
                },
            });
            inserted += 1;
            logger.info('inserted isbn=%s', b.isbn);
        } catch (err) {
            // err ist unknown; für das Logger-API casten wir auf object
            logger.error(
                'Fehler beim Einfügen isbn=%s: %o',
                b.isbn,
                err as object,
            );
        }
    }

    logger.info(
        'Seeding finished, inserted=%d, total=%d',
        inserted,
        books.length,
    );
};

export default seedDatabase;
